### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by willyd** [hipacc/hipacc#4]
Can hipacc work on windows?

**Comment by richardmembarth** [comment]
Yes, hipacc should work on windows. There should be nothing that prevents you from building and running hipacc on windows.
The easiest way will be to use mingw.
You can even link against a pre-build clang/llvm.
There were problems building earlier versions of clang/llvm using msvc, but this has somewhat improved.

**Comment by richardmembarth** [comment]
Great to hear that it works using mingw. In case you provide patches/merge requests for the ```execute_process``` and ```fscyn``` issues, I'll merge them.

In order to use CUDA, you don't need to build hipacc using MSVC:
- use hipacc to generate the .cu files
- use MSVC to compile the generated .cu files

**Comment by willyd** [comment]
> Great to hear that it works using mingw. In case you provide patches/merge requests for the execute_process and fscyn issues, I'll merge them.

Sure.

> In order to use CUDA, you don't need to build hipacc using MSVC:
> 
>     use hipacc to generate the .cu files
>     use MSVC to compile the generated .cu files

Thanks for the tip.

**Comment by richardmembarth** [comment]
I've updated the installation section to mention requirements to build Hipacc on Windows.

Note that fsync is supported in msys2 - you need to install the required development packages.
