### ISSUE TITLE
problem with hipacc data types

### ISSUE THREAD

**Issue by babouFomb** [hipacc/hipacc#6]
I started learning HIPAcc it just 2 days, so I'm a little new there in.
I wanted to bring my c ++ version of the sobel to HIPAcc using the example available in the "test" directory of HIPAcc.
Nevertheless, I encounter a problem, the output images of the HIPAcc version differ from the outputs of the c ++ version. I use the same types for both versions.
I 
[hipacc_sobel.tar.gz](https://github.com/hipacc/hipacc/files/847567/hipacc_sobel.tar.gz)
attach to the message is the code, the CMakelist that I use to compile, the output images and the input image.
Thank you.

**Comment by richardmembarth** [comment]
Your C++ implementation computes differently from the Hipacc implementation:
- only in C++: >> 2 + 128
- incorrect in C++: scale misses the else branch
Fixing those yields the same results.

**Comment by babouFomb** [comment]
Yes, You are right, indeed by adding:
`int16_t pixel = input();`
`pixel = (pixel >> 2) + 128;`
To scale before testing the pixel value, the output of HIPAcc is identical to that obtained with the c ++ implementation.
Thank you.
